### ISSUE TITLE
"Best Practices" section in initial report

### ISSUE THREAD

**Issue by ThisIsMissEm** [swicg/activitypub-trust-and-safety#31]
This came via @julianlam in the AP Trust & Safety taskforce meeting today

Let's come up with some notes on general best practices for Trust & Safety that we can document in the initial report.

Some ideas:
- Recommendation to prefer human moderation, or at least human review of moderation decisions
- Encourage collaborative approaches to moderation: you don't need to just throw a Flag over to another server, you can actively reach out and try to communicate with instances.
- Encourage software implement federation management, i.e., prevent processing activities from certain domains (whilst acknowledging that we won't be tackling federating federation management decisions at this time)
- Encourage software to implement basic reporting capabilities and general UI recommendations for displaying reports to moderators (i.e., blur / greyscale / don't auto-play media )

Please leave comments with additional thoughts.

**Comment by ThisIsMissEm** [comment]
Whoops, this duplicates #29

**Comment by jmking-iftas** [comment]
We have some reporting workflow guidance in https://connect.iftas.org/library/tools-resources/information-for-software-developers-and-designers/, and a forthcoming Moderator Manual has a ton of best practice, anticipate a v1.0 by year end 24.
