### ISSUE TITLE
Setup taskforce README & meetings

### ISSUE THREAD

**Issue by ThisIsMissEm** [swicg/activitypub-trust-and-safety#5]
- [x] need to flesh out the readme with more information about the taskforce, the various focus areas, and outcomes
- [x] setup scaffold for report website 
- [x] need to finish scheduling the monthly meetings for the taskforce with W3C / SWICG
- [ ] need to better understand what we can do within the scope of the taskforce's report vs what needs to be done as FEPs

**Comment by ThisIsMissEm** [comment]
@dmitrizagidulin is there more information about running a taskforce anywhere? I looked and couldn't find anything.

**Comment by angusmcleod** [comment]
Please include me in any meeting invites :)

**Comment by julianlam** [comment]
Likewise, we'd be interested in developments re: T&S.

@angusmcleod and I used a scheduling app to see common availabilities, and we're hosting discussions on fedi itself (organized via either NodeBB or Discourse's respective categories for WG content).  However, we are unique in doing it this way.

Happy to make space (a new category?) for you there. No idea if we're doing things the right way, but as long as the self-described goals are met...

**Comment by ThisIsMissEm** [comment]
> we're hosting discussions on fedi itself (organized via either NodeBB or Discourse's respective categories for WG content). However, we are unique in doing it this way.
> 
> Happy to make space (a new category?) for you there. No idea if we're doing things the right way, but as long as the self-described goals are met...

@julianlam for now I'm just using GitHub Issues to organise and get down some potential work items, which would eventually evolve into discussions and FEPs and research and what not. Just wanted to set a bit of a direction for the taskforce by bringing across issues maintained elsewhere to help us get started.

**Comment by ThisIsMissEm** [comment]
Am going to go ahead and close this now we have #26 and the [first meeting](https://lists.w3.org/Archives/Public/public-swicg/2024Nov/0031.html).
